version: "3.7"
services:
    nginx:
        build: ./nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./.logs/:/etc/logs/
            - /etc/letsencrypt/live/:/etc/certs/
            - /etc/letsencrypt/archive:/etc/archive/
        restart: always
        depends_on:
            - web
            - api
        ports:
            - "80:80"
            - "443:443"
    web:
        build: ./web
        env_file:
            - ./.env
        volumes:
            - ./web/src/:/usr/src/app/src/
            - ./web/public/:/usr/src/app/public/
            - ./web/views/:/usr/src/app/views/
            - /var/www/certbot/:/usr/src/app/www/
        restart: always
    api:
        build: ./api
        env_file:
            - ./.env
        volumes:
            - ./api/src/:/usr/src/app/src/
            - ./.certs/:/usr/src/app/.certs/
            - /var/www/certbot/:/usr/src/app/www/
        restart: always

